sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules


node_js:
  - "6"
  - "7"
  - "node"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm uninstall -g babel
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm run coverage
